resources:
- name: resource-tutorial
  type: git
  source:
    uri: git@github.com:DH-TB/spring-boot-base.git
    private_key: ((private-repo-key))    # (())引用变量

jobs:
- name: job-name
  public: true
  plan:
  - get: resource-tutorial
  - task: test
    file: resource-tutorial/test.yml