jobs:
- name: pipeline-name
  plan:
  - task: say-pipeline
    trigger: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello, world!"]